In [1]:
import numpy as np
import pandas as pd

In [6]:
# How a basic neuron works 3 inputs
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

4.8


In [ ]:
# How a basic neuron works 4 inputs
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

In [8]:
# 3 neurons, 4 inputs, no loops -_-
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3,
         ]
print(output)

[4.8, 1.21, 2.385]


In [11]:
# 3 neurons, 4 inputs, wiff loops
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87],
            ]

biases = [2, 3, 0.5]

# Create a list to hold all of out outputs
layer_output = []

# Iterate over the weights and biases
for neuron_weights, neuron_bias in zip(weights, biases):
    # Initialise the output of a neuron
    neuron_output = 0
    # iterate over the weights in the given neuron and the input
    for n_input, weight in zip(inputs, neuron_weights):
        # Times the weight by the input
        neuron_output += n_input*weight
    # Add the bias and append to the list of outputs
    neuron_output += neuron_bias
    layer_output.append(neuron_output)

print(output)

[4.8, 1.21, 2.385]


In [12]:
# Dot product style with a neuron
inputs = [1, 2, 3, 2.5]

weights = [0.2, 0.8, -0.5, 1.0]

bias = 2

output = np.dot(weights, inputs) + bias

print(output)

4.8


In [15]:
# Dot product style with a layer of neurons
inputs = [1, 2, 3, 2.5]

weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
    ]

biases = [2, 3, 0.5]
    
outputs = np.dot(weights, inputs) + biases

print(output)

[4.8   1.21  2.385]


In [17]:
# Bacth time with  Dot product style with a layer of neurons
inputs = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8],
    ]
        
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
    ]

biases = [2, 3, 0.5]
    
output = np.dot(inputs, np.array(weights).T) + biases

print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [18]:
# Bacth time with  Dot product style with Multiple layers of neurons
inputs = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8],
    ]
        
weights1 = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
    ]

biases1 = [2, 3, 0.5]

weights2 = [
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13],
    ]

biases2 = [-1, 2, -0.5]
    
layer1_outputs = np.dot(inputs, np.array(weights1).T) + biases1

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2


print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [59]:
# Creating the softmax function

# our outputs from the final layer
layer_outputs = [[4.8, 1.21, 2.385],
                [8.9, -1.81, 0.2],
                [1.41, 1.051, 0.026]]

# Getting all output values risen by Eulers number to rid us of negs and hold scale
exp_values = np.exp(layer_outputs)




# For each exp_output divide it by the sum of all exp_outputs to get the ratio against the other outputs
norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)
norm_values


array([[8.95282664e-01, 2.47083068e-02, 8.00090293e-02],
       [9.99811129e-01, 2.23163963e-05, 1.66554348e-04],
       [5.13097164e-01, 3.58333899e-01, 1.28568936e-01]])

In [79]:
# Categorical cross entrpohy example
import math

softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]

loss = -(math.log(softmax_output[0])*target_output[0] +
        math.log(softmax_output[1])*target_output[1]  +
        math.log(softmax_output[2])*target_output[2])

# print(loss)

softmax_outputs = np.array([[0.2, 0.1, 0.2],
                           [0.1, 0.5, 0.4],
                           [0.02, 0.9, 0.08]])

class_targets = [0, 1, 1]

-np.log(softmax_outputs[[0,1,2], class_targets])

array([1.60943791, 0.69314718, 0.10536052])

# Main Network cells

In [27]:
# Creating a random dataset for the network test, debugging, building, etc
np.random.seed(0)

def create_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype="uint8")
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y

In [73]:
# Time to turn layers into objects as this is getting out of hand

class Layer_Dense:
    
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


class Activation_Softmax():
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values , axis=1, keepdims=True)
        self.output = probabilities


class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss


class Loss_CategoricalCrossentrophy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods


# Our data set from above
X, y = create_data(100, 3)

input_shape = X.shape[1]

dense1 = Layer_Dense(input_shape, 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function = Loss_CategoricalCrossentrophy()
loss = loss_function.calculate(activation2.output, y)

loss

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33334031 0.33335691 0.33330279]
 [0.33333333 0.33333333 0.33333333]]


1.0985751180932828